---
# tasks file for ansible-role-routed-lb

- name: Set fact for a unique list of VIPs
  ansible.builtin.set_fact:
    vips: "{{ (vips | default([]) + (item.vips | default([]))) | unique }}"
  with_items: "{{ configs[config].services }}"

- name: Set fact for lists of IPv4 and IPv6 VIPs
  ansible.builtin.set_fact:
    vips_v4: "{{ vips | ansible.utils.ipv4 | default([]) }}"
    vips_v6: "{{ vips | ansible.utils.ipv6 | default([]) }}"

- name: Set haproxy_connect_any flag on and keep it persistent across reboots
  ansible.posix.seboolean:
    name: haproxy_connect_any
    state: true
    persistent: true

- name: Install HAproxy
  ansible.builtin.package:
    name: haproxy
    state: present

- name: Configure HAproxy
  ansible.builtin.template:
    src: ./templates/haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: '640'

- name: Enable and start HAproxy
  ansible.builtin.service:
    name: haproxy
    enabled: true
    state: restarted

- name: Optionally deploy FRR
  when:
    - (configs[config].bgp_neighbors | default([]) | length) > 0
    - (vips | default([]) | length ) > 0
  block:
    - name: Install FRR
      ansible.builtin.package:
        name: frr
        state: present

    - name: Enable FRR BGP daemon
      ansible.builtin.lineinfile:
        path: /etc/frr/daemons
        regexp: "^bgpd="
        line: "bgpd=yes"
        owner: frr
        group: frr
        mode: '640'

    - name: Enable FRR BFD daemon
      ansible.builtin.lineinfile:
        path: /etc/frr/daemons
        regexp: "^bfdd="
        line: "bfdd=yes"
        owner: frr
        group: frr
        mode: '640'

    - name: Configure FRR
      ansible.builtin.template:
        src: ./templates/frr.conf.j2
        dest: /etc/frr/frr.conf
        owner: frr
        group: frr
        mode: '640'

    - name: Enable and start FRR
      ansible.builtin.service:
        name: frr
        enabled: true
        state: restarted

- name: Optionally manage the VIPs
  when:
    - (vips | default([]) | length ) > 0
  block:
    - name: Create script to manage the VIPs
      ansible.builtin.template:
        src: "templates/vips.sh.j2"
        dest: "/opt/vips.sh"
        owner: root
        group: root
        mode: '0744'

    - name: Create systemd unit to manage the VIPs
      ansible.builtin.template:
        src: "files/vips.service"
        dest: "/etc/systemd/system/vips.service"
        owner: root
        group: root
        mode: '0644'

    - name: Activate the VIPs service
      ansible.builtin.systemd:
        name: "vips.service"
        enabled: true
        state: restarted
        daemon_reload: true
